[package]
name = "gflags-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inventory = "0.3.2"
getopts = "0.2.21"

[workspace]
members = ["example"]